// Generated by CoffeeScript 1.10.0
Meteor.publish('posts', function() {
  return Posts.find();
});

Meteor.publish('comments', function(postId) {
  check(postId, String);
  return Comments.find({
    postId: postId
  });
});

//# sourceMappingURL=publications.js.map
