// Generated by CoffeeScript 1.10.0
Meteor.publish('posts', function() {
  return Posts.find();
});

Meteor.publish('comments', function() {
  return Comments.find();
});

//# sourceMappingURL=publications.js.map
