// Generated by CoffeeScript 1.10.0
(function() {
  if (Meteor.isClient) {
    Router.route('/', {
      name: 'postList'
    });
    Router.configure({
      layoutTemplate: 'layout',
      loadingTemplate: 'loading',
      waitOn: function() {
        return Meteor.subscribe('posts');
      }
    });
  }

}).call(this);

//# sourceMappingURL=router.js.map
