// Generated by CoffeeScript 1.10.0
var requireLogin;

Router.configure({
  layoutTemplate: 'layout',
  loadingTemplate: 'loading',
  notFoundTemplate: 'notFound',
  waitOn: function() {
    return Meteor.subscribe('posts');
  }
});

Router.map(function() {
  this.route('postList', {
    path: '/'
  });
  this.route('postPage', {
    path: '/posts/:_id',
    data: function() {
      return Posts.findOne(this.params._id);
    }
  });
  this.route('postEdit', {
    path: '/post/:_id/edit',
    data: function() {
      return Posts.findOne(this.params._id);
    }
  });
  return this.route('postSubmit', {
    path: '/submit'
  });
});

requireLogin = function() {
  if (!Meteor.user()) {
    if (Meteor.loggingIn()) {
      this.render(this.loadingTemplate);
    } else {
      this.render('accessDenied');
    }
  } else {
    this.next();
  }
};

Router.onBeforeAction('dataNotFound', {
  only: 'postPage'
});

Router.onBeforeAction(requireLogin, {
  only: 'postSubmit'
});

//# sourceMappingURL=router.js.map
