// Generated by CoffeeScript 1.10.0
var requireLogin;

if (Meteor.isClient) {
  Router.configure({
    layoutTemplate: 'layout',
    loadingTemplate: 'loading',
    notFoundTemplate: 'notFound',
    waitOn: function() {
      return Meteor.subscribe('posts');
    }
  });
  Router.route('/', {
    name: 'postList'
  });
  Router.route('/posts/:_id', {
    name: 'postPage',
    data: function() {
      return Posts.findOne(this.params._id);
    }
  });
  Router.route('/submit', {
    name: 'postSubmit'
  });
  requireLogin = function() {
    if (!Meteor.user()) {
      if (Meteor.loggingIn()) {
        this.render(this.loadingTemplate);
      } else {
        this.render('accessDenied');
      }
    } else {
      this.next();
    }
  };
  Router.onBeforeAction('dataNotFound', {
    only: 'postPage'
  });
  Router.onBeforeAction(requireLogin, {
    only: 'postSubmit'
  });
}

//# sourceMappingURL=router.js.map
