// Generated by CoffeeScript 1.10.0
(function() {
  var postData;

  postData = [
    {
      title: 'Introducing Telescope',
      url: 'http://sachagreif.com/introducing-telescope/'
    }, {
      title: 'Meteor',
      url: 'http://meteor.com'
    }, {
      title: 'The Meteor Book',
      url: 'http://themeteorbook.com'
    }
  ];

  Template.postList.helpers({
    posts: postData
  });

}).call(this);

//# sourceMappingURL=post_list.js.map
