// Generated by CoffeeScript 1.10.0
Template.postItem.helpers({
  domain: function() {
    var a;
    a = document.createElement('a');
    a.href = this.url;
    return a.hostname;
  }
});

//# sourceMappingURL=post_item.js.map
